config/routes.rb
Rails.application.routes.draw do
  get 'mypage', to: 'users#show'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :artists do
    collection do
      get :favorites
      get :list
    end
    resources :members, only: [:index, :destroy]
    member do
      post 'toggle_favorite'
    end
  end
  resources :live_schedules do
    collection do
      get :planned
      get :records
    end
    resources :venues, only: [:new, :create]
  end
  resources :goods do
    collection do
      get :list
    end
    resources :categories, only: [:new, :create]
  end
  get 'statistics', to: 'statistics#index'
  get 'statistics/live', to: 'statistics#live'
  get 'statistics/goods', to: 'statistics#goods'
  get 'statistics/artists', to: 'statistics#artists'
  root 'home#index'
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :user
  has_many :members, dependent: :destroy
  has_many :live_records, -> { attended }, class_name: "LiveSchedule", dependent: :nullify
  has_many :live_schedules, dependent: :nullify
  has_many :goods, dependent: :nullify
  accepts_nested_attributes_for :members, allow_destroy: true, reject_if: :all_blank
  mount_uploader :image, AvatarUploader
  validates :name, presence: true, length: { maximum: 25 }
  validates :nickname, length: { maximum: 10 }
  validate :nickname_required_if_mode_on
  validate :founding_date_not_in_future
  validate :first_show_date_after_founding_date
  validate :first_show_date_not_in_future

  def display_name
    nickname_mode && nickname.present? ? nickname : name
  end

  def non_display_name
    nickname_mode && nickname.present? ? name : nickname
  end

  def combined_name
    return display_name if non_display_name.blank?

    "#{display_name}(#{non_display_name})"
  end

  private

  def nickname_required_if_mode_on
    return unless nickname_mode && nickname.blank?

    errors.add(:nickname, "ニックネームモードが有効の場合、ニックネームは必須です")
  end

  def founding_date_not_in_future
    return unless founding_date && founding_date > Time.zone.today

    errors.add(:founding_date, "結成日は今日より前に設定してください")
  end

  def first_show_date_after_founding_date
    return unless founding_date && first_show_date && first_show_date < founding_date

    errors.add(:first_show_date, "初めて見た日は結成日より前に設定することはできません")
  end

  def first_show_date_not_in_future
    return unless first_show_date && first_show_date > Time.zone.today

    errors.add(:first_show_date, "初めて見た日は今日より前に設定してください")
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_artist, only: [:show, :edit, :update, :destroy, :toggle_favorite]

  def index
    artists_scope = current_user.artists.order(created_at: :desc)
    @artists = artists_scope.to_a
    @recent_artists = artists_scope.limit(3)
    @artist = current_user.artists.build
  end

  def show
    @display_attributes = {
      "アーティスト名" => @artist.name,
      "ニックネーム" => @artist.nickname,
      "ジャンル" => @artist.genre,
      "結成日" => @artist.founding_date,
      "初ライブ日" => @artist.first_show_date,
      "メモ" => @artist.memo
    }.select { |_, value| value.present? }
  end

  def new
    @artist = Artist.new
  end

  def list
    @artists = current_user.artists.order(created_at: :desc)
  end

  def edit
  end

  def create
    @artist = current_user.artists.build(artist_params)
    if @artist.save
      redirect_target = (params[:artist][:from].presence || artists_path)
      redirect_to "#{redirect_target}?selected_artist_id=#{@artist.id}", notice: "アーティストを作成しました。"
    else
      artists_scope = current_user.artists.order(created_at: :desc)
      @artists = artists_scope.to_a
      @recent_artists = artists_scope.limit(3)
      render 'index'
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_target = (params[:artist][:from].presence || artists_path)
      redirect_to "#{redirect_target}?selected_artist_id=#{@artist.id}"
    else
      render 'edit'
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path, notice: "アーティストを削除しました。"
  end

  def favorites
    @favorite_artists = current_user.artists.where(favorited: true)
  end

  def toggle_favorite
    @artist.update!(favorited: !@artist.favorited)
    respond_to do |format|
      format.js
    end
  end

  private

  def set_artist
    @artist = current_user.artists.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name, :nickname, :image, :genre, :memo, :nickname_mode, :favorited, :founding_date, :first_show_date, { members_attributes: [:id, :name, :_destroy] })
  end
end

app/views/artists/destroy.js.erb
$("#member_<%= @member.id %>").remove();

app/views/artists/edit.html.erb
<%= render "shared/artist_form_card", artist: @artist %>

app/views/artists/favorites.html.erb
<div class="main-container">
  <div class="artist-index">
    <div class="mb-4 d-flex justify-content-between">
      <%= link_to new_artist_path, class: "btn btn-success btn-lg mr-3" do %>
        <i class="fas fa-plus-circle"></i> 新規アーティスト作成
      <% end %>
      <%= link_to artists_path, class: "btn btn-info btn-lg" do %>
        全アーティスト一覧
      <% end %>
    </div>
    <div class="row">
      <% @favorite_artists.each do |artist| %>
        <div class="col-md-4">
          <div class="card mb-4 clickable" data-href="<%= artist_path(artist) %>">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center">
                <h5 class="card-title mb-0">
                  <%= artist.combined_name %>
                </h5>
                <%= link_to "編集", edit_artist_path(artist), class: "btn btn-primary" %>
              </div>
              <div class="d-flex justify-content-between align-items-center mt-2">
                <p class="card-text mb-0">作成日: <%= artist.created_at.strftime("%Y-%m-%d") %></p>
                <%= link_to "削除", artist, method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/artists/index.html.erb
<div class="main-container artists-index">
  <div class="artists-index__header">
    <div class="artists-index__title">アーティスト</div>
  </div>
  <section class="artists-index__section artists-index__section--form">
    <div class="artists-index__form live-form artist-form">
      <%= render "shared/artist_form_card", artist: @artist %>
    </div>
  </section>
  <section class="artists-index__section">
    <div class="artists-index__section-header">
      <h2 class="artists-index__section-title">最近登録したアーティスト</h2>
      <div class="artists-index__section-actions">
        <%= link_to "アーティスト一覧→", list_artists_path, class: "artists-index__link" %>
      </div>
    </div>
    <% if @recent_artists.any? %>
      <div class="artists-list">
        <% @recent_artists.each do |artist| %>
          <div class="artists-card clickable" data-href="<%= artist_path(artist) %>">
            <div class="artists-card__header">
              <div class="artists-card__title"><%= artist.combined_name %></div>
              <div class="artists-card__actions">
                <%= link_to edit_artist_path(artist), class: "artists-card__action" do %>
                  <i class="fas fa-edit"></i>
                <% end %>
                <%= link_to artist, method: :delete, data: { confirm: "本当に削除しますか？" }, class: "artists-card__action" do %>
                  <i class="fa fa-trash"></i>
                <% end %>
              </div>
            </div>
            <div class="artists-card__meta">
              <span>作成日: <%= artist.created_at.strftime("%Y-%m-%d") %></span>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="artists-index__empty">まだ登録がありません</div>
    <% end %>
  </section>
</div>

app/views/artists/list.html.erb
<div class="main-container artists-index">
  <div class="artists-index__header">
    <div class="artists-index__title">アーティスト一覧</div>
  </div>
  <section class="artists-index__section">
    <div class="artists-index__section-header">
      <h2 class="artists-index__section-title">すべてのアーティスト</h2>
    </div>
    <% if @artists.any? %>
      <div class="artists-list">
        <% @artists.each do |artist| %>
          <div class="artists-card clickable" data-href="<%= artist_path(artist) %>">
            <div class="artists-card__header">
              <div class="artists-card__title"><%= artist.combined_name %></div>
              <div class="artists-card__actions">
                <%= link_to edit_artist_path(artist), class: "artists-card__action" do %>
                  <i class="fas fa-edit"></i>
                <% end %>
                <%= link_to artist, method: :delete, data: { confirm: "本当に削除しますか？" }, class: "artists-card__action" do %>
                  <i class="fa fa-trash"></i>
                <% end %>
              </div>
            </div>
            <div class="artists-card__meta">
              <span>作成日: <%= artist.created_at.strftime("%Y-%m-%d") %></span>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="artists-index__empty">まだ登録がありません</div>
    <% end %>
  </section>
</div>

app/views/artists/new.html.erb
<%= render "shared/artist_form_card", artist: @artist %>

app/views/artists/show.html.erb
<div class="main-container artist-detail">
  <div class="artist-detail__hero">
    <div class="artist-detail__main">
      <div class="artist-detail__title-row">
        <h1 class="artist-detail__title"><%= @artist.combined_name %></h1>
        <%= link_to toggle_favorite_artist_path(@artist), remote: true, method: :post, class: "artist-detail__favorite" do %>
          <% if @artist.favorited? %>
            <i class="fas fa-heart heart-pink"></i>
          <% else %>
            <i class="fas fa-heart heart-black"></i>
          <% end %>
        <% end %>
      </div>
      <% if @artist.nickname.present? && @artist.nickname_mode? %>
        <div class="artist-detail__subtitle"><%= @artist.nickname %></div>
      <% end %>
      <div class="artist-detail__meta">
        <% if @artist.genre.present? %>
          <span>ジャンル: <%= @artist.genre %></span>
        <% end %>
        <% if @artist.founding_date.present? %>
          <span>結成日: <%= @artist.founding_date %> (<%= days_since(@artist.founding_date) %>日目)</span>
        <% end %>
        <% if @artist.first_show_date.present? %>
          <span>初ライブ参加日: <%= @artist.first_show_date %> (<%= days_since(@artist.first_show_date) %>日目)</span>
        <% end %>
      </div>
    </div>
    <div class="artist-detail__actions">
      <%= link_to edit_artist_path(@artist), class: "artist-detail__action artist-detail__action--edit" do %>
        <i class="fas fa-edit"></i> 編集
      <% end %>
      <%= link_to artist_path(@artist), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "artist-detail__action artist-detail__action--delete" do %>
        <i class="fas fa-trash-alt"></i> 削除
      <% end %>
    </div>
  </div>
  <div class="artist-detail__grid">
    <section class="artist-card artist-card--members">
      <h2 class="artist-card__title">メンバー</h2>
      <% if @artist.members.any? %>
        <div class="artist-members">
          <% @artist.members.each do |member| %>
            <div class="artist-member__item" id="member_<%= member.id %>">
              <span><%= member.name %></span>
              <%= link_to artist_member_path(@artist, member), method: :delete, remote: true, data: { confirm: "本当に削除しますか？" }, class: "artist-member__delete" do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            </div>
          <% end %>
        </div>
      <% else %>
        <div class="artist-card__empty">メンバーは未登録です</div>
      <% end %>
    </section>
    <section class="artist-card artist-card--image">
      <h2 class="artist-card__title">画像</h2>
      <% if @artist.image.present? && @artist.image? %>
        <div class="artist-image__frame">
          <%= image_tag(@artist.image.url, class: "artist-image__img") %>
        </div>
      <% else %>
        <div class="artist-card__empty">画像がありません</div>
      <% end %>
    </section>
    <section class="artist-card artist-card--memo">
      <h2 class="artist-card__title">メモ</h2>
      <% if @artist.memo.present? %>
        <div class="artist-card__memo"><%= simple_format(@artist.memo) %></div>
      <% else %>
        <div class="artist-card__empty">メモは未登録です</div>
      <% end %>
    </section>
  </div>
</div>

app/views/artists/toggle_favorite.js.erb
<% if @artist.favorited? %>
  $(".fa-heart").removeClass("heart-black").addClass("heart-pink");
<% else %>
  $(".fa-heart").removeClass("heart-pink").addClass("heart-black");
<% end %>